"""Add ballot number to elector submission record

Revision ID: 1f94a43bb6b7
Revises: 70e6e00d7260
Create Date: 2026-08-04 11:47:46.507542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f94a43bb6b7'
down_revision = '70e6e00d7260'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('elector_submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ballot_number', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('elector_submission', schema=None) as batch_op:
        batch_op.drop_column('ballot_number')

    # ### end Alembic commands ###
