"""Add ballot pen code

Revision ID: 22e2592ffc4c
Revises: 2648cc5fcd58
Create Date: 2026-07-15 12:28:21.599684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22e2592ffc4c'
down_revision = '2648cc5fcd58'
branch_labels = None
depends_on = None


def upgrade():

    op.execute("""
        UPDATE ballot_pen
        SET code = 'BP-' || id
        WHERE code IS NULL
    """)

    with op.batch_alter_table('ballot_pen', schema=None) as batch_op:

        batch_op.alter_column(
            'code',
            existing_type=sa.String(length=50),
            nullable=False
        )

        batch_op.create_unique_constraint(
            "uq_ballot_pen_code",
            ['code']
        )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ballot_pen', schema=None) as batch_op:
        batch_op.drop_constraint("uq_ballot_pen_code", type_='unique')
        batch_op.drop_column('code')

    # ### end Alembic commands ###
