"""Add polling center and rooms

Revision ID: 2648cc5fcd58
Revises: 46efe2e134b2
Create Date: 2026-07-10 15:07:23.818865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2648cc5fcd58'
down_revision = '46efe2e134b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ballot_pen', schema=None) as batch_op:
        batch_op.add_column(sa.Column('polling_center_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('room_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_ballot_pen_polling_center_id", 'polling_centers', ['polling_center_id'], ['id'])
        batch_op.create_foreign_key("fk_ballot_pen_room_id", 'rooms', ['room_id'], ['id'])
        batch_op.drop_column('polling_center')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ballot_pen', schema=None) as batch_op:
        batch_op.add_column(sa.Column('polling_center', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint("fk_ballot_pen_polling_center_id", type_='foreignkey')
        batch_op.drop_constraint("fk_ballot_pen_room_id", type_='foreignkey')
        batch_op.drop_column('room_id')
        batch_op.drop_column('polling_center_id')

    # ### end Alembic commands ###
