"""Add foreign keys

Revision ID: 2852d5072f38
Revises: 167657ad8299
Create Date: 2026-06-23 14:48:06.583732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2852d5072f38'
down_revision = '167657ad8299'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('district_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ballot_pen_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_district', 'district', ['district_id'], ['id'])
        batch_op.create_foreign_key('fk_tenant', 'tenant', ['tenant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_district', type_='foreignkey')
        batch_op.drop_constraint('fk_tenant', type_='foreignkey')
        batch_op.drop_column('ballot_pen_id')
        batch_op.drop_column('district_id')
        batch_op.drop_column('tenant_id')

    # ### end Alembic commands ###
