"""Change models

Revision ID: 3ace1f356021
Revises: 937c2176f84f
Create Date: 2026-06-25 13:19:07.770601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ace1f356021'
down_revision = '937c2176f84f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sect', schema=None) as batch_op:
        batch_op.add_column(sa.Column('religion_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_sect_religion', 'religion', ['religion_id'], ['id'])
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sect', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint('fk_sect_religion', type_='foreignkey')
        batch_op.drop_column('religion_id')

    # ### end Alembic commands ###
