"""Fix BallotPen and BallotPenSect models

Revision ID: 46efe2e134b2
Revises: bb1b97ce9800
Create Date: 2026-07-10 12:39:05.368948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46efe2e134b2'
down_revision = 'bb1b97ce9800'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ballot_pen_sect', schema=None) as batch_op:
        batch_op.add_column(sa.Column('register_from', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('register_to', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('register_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ballot_pen_sect', schema=None) as batch_op:
        batch_op.drop_column('register_count')
        batch_op.drop_column('register_to')
        batch_op.drop_column('register_from')

    # ### end Alembic commands ###
