"""Update elector model with sect and ballot pen relations

Revision ID: 4a70c6d470f5
Revises: aef93f902d0b
Create Date: 2026-08-03 17:15:13.164761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a70c6d470f5'
down_revision = 'aef93f902d0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('elector', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_elector_elector_id'), ['elector_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('elector', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_elector_elector_id'))

    # ### end Alembic commands ###
