"""Add description to subdistrict

Revision ID: 521ac38f1aa8
Revises: c0d3a9696653
Create Date: 2026-06-26 12:18:26.186567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '521ac38f1aa8'
down_revision = 'c0d3a9696653'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subdistrict', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subdistrict', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
