"""Move elector submission to tenant

Revision ID: 557a8a09a750
Revises: 1f94a43bb6b7
Create Date: 2026-08-05 10:12:12.117208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '557a8a09a750'
down_revision = '1f94a43bb6b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('elector_submission')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('elector_submission',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('elector_id', sa.INTEGER(), nullable=False),
    sa.Column('elector_code', sa.VARCHAR(length=120), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=120), nullable=True),
    sa.Column('surname', sa.VARCHAR(length=120), nullable=True),
    sa.Column('submitted_at', sa.DATETIME(), nullable=False),
    sa.Column('district_id', sa.INTEGER(), nullable=True),
    sa.Column('district_name', sa.VARCHAR(length=120), nullable=True),
    sa.Column('subdistrict_id', sa.INTEGER(), nullable=True),
    sa.Column('subdistrict_name', sa.VARCHAR(length=120), nullable=True),
    sa.Column('municipality', sa.VARCHAR(length=120), nullable=True),
    sa.Column('ballot_pen_id', sa.INTEGER(), nullable=True),
    sa.Column('polling_center_name', sa.VARCHAR(length=150), nullable=True),
    sa.Column('room_name', sa.VARCHAR(length=150), nullable=True),
    sa.Column('ballot_number', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['elector_id'], ['elector.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
