"""Make district id nullable in subdistrict

Revision ID: 684ab4351395
Revises: 521ac38f1aa8
Create Date: 2026-06-26 14:27:50.076022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '684ab4351395'
down_revision = '521ac38f1aa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subdistrict', schema=None) as batch_op:
        batch_op.alter_column('district_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subdistrict', schema=None) as batch_op:
        batch_op.alter_column('district_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
