"""New schema

Revision ID: 6d4a31da0866
Revises: b8e06e75c837
Create Date: 2026-07-23 16:33:40.486752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d4a31da0866'
down_revision = 'b8e06e75c837'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vote')
    op.drop_table('candidate_list')
    op.drop_table('ballot_pen_account')
    op.drop_table('candidate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('candidate_list_id', sa.INTEGER(), nullable=True),
    sa.Column('district_id', sa.INTEGER(), nullable=True),
    sa.Column('subdistrict_id', sa.INTEGER(), nullable=True),
    sa.Column('sect_id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ballot_pen_account',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ballot_pen_id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), nullable=False),
    sa.Column('active_session_token', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['ballot_pen_id'], ['ballot_pen.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('candidate_list',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('district_id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vote',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('elector_id', sa.INTEGER(), nullable=True),
    sa.Column('ballot_pen_id', sa.INTEGER(), nullable=True),
    sa.Column('district_id', sa.INTEGER(), nullable=True),
    sa.Column('subdistrict_id', sa.INTEGER(), nullable=True),
    sa.Column('sect_id', sa.INTEGER(), nullable=True),
    sa.Column('list_id', sa.INTEGER(), nullable=True),
    sa.Column('candidate_id', sa.INTEGER(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
