"""Add ballot number

Revision ID: 70e6e00d7260
Revises: 4a70c6d470f5
Create Date: 2026-08-04 09:00:41.533813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70e6e00d7260'
down_revision = '4a70c6d470f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('elector', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ballot_number', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('elector', schema=None) as batch_op:
        batch_op.drop_column('ballot_number')

    # ### end Alembic commands ###
