"""Add canceled paper class

Revision ID: 903ebcc64bc2
Revises: ff23c634d4d7
Create Date: 2026-08-21 14:08:57.280716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '903ebcc64bc2'
down_revision = 'ff23c634d4d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('district_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['district.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.drop_table('vote')
    op.drop_table('candidate_list')
    op.drop_table('elector_submission')
    op.drop_table('political_allegiance')
    op.drop_table('candidate')
    op.drop_table('ballot_pen_account')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ballot_pen_account',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ballot_pen_id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), nullable=False),
    sa.Column('active_session_token', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('candidate',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('candidate_list_id', sa.INTEGER(), nullable=False),
    sa.Column('district_id', sa.INTEGER(), nullable=True),
    sa.Column('subdistrict_id', sa.INTEGER(), nullable=True),
    sa.Column('sect_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), nullable=True),
    sa.Column('political_allegiance_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_list_id'], ['candidate_list.id'], ),
    sa.ForeignKeyConstraint(['political_allegiance_id'], ['political_allegiance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('political_allegiance',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('district_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('elector_submission',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('elector_id', sa.INTEGER(), nullable=False),
    sa.Column('elector_code', sa.VARCHAR(length=120), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=120), nullable=True),
    sa.Column('surname', sa.VARCHAR(length=120), nullable=True),
    sa.Column('submitted_at', sa.DATETIME(), nullable=False),
    sa.Column('district_id', sa.INTEGER(), nullable=True),
    sa.Column('district_name', sa.VARCHAR(length=120), nullable=True),
    sa.Column('subdistrict_id', sa.INTEGER(), nullable=True),
    sa.Column('subdistrict_name', sa.VARCHAR(length=120), nullable=True),
    sa.Column('municipality', sa.VARCHAR(length=120), nullable=True),
    sa.Column('ballot_pen_id', sa.INTEGER(), nullable=True),
    sa.Column('ballot_number', sa.INTEGER(), nullable=True),
    sa.Column('polling_center_name', sa.VARCHAR(length=150), nullable=True),
    sa.Column('room_name', sa.VARCHAR(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate_list',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('district_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vote',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('elector_id', sa.INTEGER(), nullable=True),
    sa.Column('ballot_pen_id', sa.INTEGER(), nullable=True),
    sa.Column('district_id', sa.INTEGER(), nullable=True),
    sa.Column('subdistrict_id', sa.INTEGER(), nullable=True),
    sa.Column('sect_id', sa.INTEGER(), nullable=True),
    sa.Column('list_id', sa.INTEGER(), nullable=True),
    sa.Column('candidate_id', sa.INTEGER(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('district_account')
    # ### end Alembic commands ###
