"""Add user ballot pen many to many

Revision ID: 90b97915e398
Revises: 6d4a31da0866
Create Date: 2026-07-24 11:57:02.558573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90b97915e398'
down_revision = '6d4a31da0866'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('ballot_pen_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ballot_pen_id', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
