"""Fix models

Revision ID: 937c2176f84f
Revises: fd99c7d19e45
Create Date: 2026-06-24 14:42:04.537286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '937c2176f84f'
down_revision = 'fd99c7d19e45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subdistrict', schema=None) as batch_op:
        batch_op.alter_column('district_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subdistrict', schema=None) as batch_op:
        batch_op.alter_column('district_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
