"""Fix elector model

Revision ID: 9b87a6ae8f53
Revises: 90b97915e398
Create Date: 2026-07-24 13:43:13.465142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b87a6ae8f53'
down_revision = '90b97915e398'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('elector', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ballot_pen_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('submitted_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key("fk_elector_ballot_pen", 'ballot_pen', ['ballot_pen_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('elector', schema=None) as batch_op:
        batch_op.drop_constraint("fk_elector_ballot_pen", type_='foreignkey')
        batch_op.drop_column('submitted_at')
        batch_op.drop_column('ballot_pen_id')

    # ### end Alembic commands ###
