"""Add elector submission table

Revision ID: aef93f902d0b
Revises: 9b87a6ae8f53
Create Date: 2026-07-24 14:58:21.073352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aef93f902d0b'
down_revision = '9b87a6ae8f53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('elector', schema=None) as batch_op:
        batch_op.drop_column('submitted_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('elector', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submitted_at', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
