"""Fix models

Revision ID: b8e06e75c837
Revises: dd4c4de37c9e
Create Date: 2026-07-23 15:35:16.991985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8e06e75c837'
down_revision = 'dd4c4de37c9e'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table("ballot_pen_account", schema=None) as batch_op:
        batch_op.drop_column("tenant_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ballot_pen_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key("fk_ballot_pen_account_ballot_pen_id_ballot_pen", 'ballot_pen', ['ballot_pen_id'], ['id'])
        batch_op.create_foreign_key("fk_ballot_pen_account_tenant_id_tenant", 'tenant', ['tenant_id'], ['id'])

    # ### end Alembic commands ###
