"""Modify models

Revision ID: bb1b97ce9800
Revises: d7f4c6075e0c
Create Date: 2026-07-09 14:27:18.887820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb1b97ce9800'
down_revision = 'd7f4c6075e0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ballot_pen', schema=None) as batch_op:
        batch_op.add_column(sa.Column('village', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('polling_center', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ballot_pen', schema=None) as batch_op:
        batch_op.drop_column('polling_center')
        batch_op.drop_column('village')

    # ### end Alembic commands ###
