"""Fix sect model and delete religion model

Revision ID: c0d3a9696653
Revises: 3ace1f356021
Create Date: 2026-06-26 11:47:00.623835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0d3a9696653'
down_revision = '3ace1f356021'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('religion')
    with op.batch_alter_table('sect', schema=None) as batch_op:
        batch_op.add_column(sa.Column('religion', sa.String(length=10), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_sect_religion'), type_='foreignkey')
        batch_op.drop_column('religion_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sect', schema=None) as batch_op:
        batch_op.add_column(sa.Column('religion_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_sect_religion'), 'religion', ['religion_id'], ['id'])
        batch_op.drop_column('religion')

    op.create_table('religion',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###
