"""Add models

Revision ID: d7f4c6075e0c
Revises: 315e112af88a
Create Date: 2026-07-08 15:54:53.832800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7f4c6075e0c'
down_revision = '315e112af88a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ballot_pen', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('voters_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.String(length=255), nullable=True))
        ###batch_op.drop_constraint("fk_ballot_pen_sect", type_='foreignkey')
        batch_op.drop_column('sect_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ballot_pen', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sect_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key("fk_ballot_pen_sect", 'sect', ['sect_id'], ['id'])
        batch_op.drop_column('notes')
        batch_op.drop_column('voters_count')
        batch_op.drop_column('gender_type')

    # ### end Alembic commands ###
