"""Add birth and current sect data

Revision ID: dd4c4de37c9e
Revises: e718c1a07dbb
Create Date: 2026-07-15 16:01:01.322484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd4c4de37c9e'
down_revision = 'e718c1a07dbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('elector', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth_sect_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('current_sect_id', sa.Integer(), nullable=True))
        batch_op.alter_column('district_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('subdistrict_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key("fk_district", 'district', ['district_id'], ['id'])
        batch_op.create_foreign_key("fk_subdistrict", 'subdistrict', ['subdistrict_id'], ['id'])
        batch_op.create_foreign_key("fk_birth_sect", 'sect', ['birth_sect_id'], ['id'])
        batch_op.create_foreign_key("fk_current_sect", 'sect', ['current_sect_id'], ['id'])
        batch_op.drop_column('sect_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('elector', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sect_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint("fk_district", type_='foreignkey')
        batch_op.drop_constraint("fk_subdistrict", type_='foreignkey')
        batch_op.drop_constraint("fk_birth_sect", type_='foreignkey')
        batch_op.drop_constraint("fk_current_sect", type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('subdistrict_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('district_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('current_sect_id')
        batch_op.drop_column('birth_sect_id')

    # ### end Alembic commands ###
