"""Delete religion ID

Revision ID: e718c1a07dbb
Revises: a3b5114e2b68
Create Date: 2026-07-15 15:42:07.340101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e718c1a07dbb'
down_revision = 'a3b5114e2b68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('elector', schema=None) as batch_op:
        batch_op.drop_column('religion_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('elector', schema=None) as batch_op:
        batch_op.add_column(sa.Column('religion_id', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
