"""New scheam

Revision ID: fd99c7d19e45
Revises: 2852d5072f38
Create Date: 2026-06-24 13:41:33.103002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd99c7d19e45'
down_revision = '2852d5072f38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('district', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=10), nullable=False))
        batch_op.create_unique_constraint('uq_district_code', ['code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('district', schema=None) as batch_op:
        batch_op.drop_constraint('uq_district_code', type_='unique')
        batch_op.drop_column('code')

    # ### end Alembic commands ###
