"""Add political allegiance

Revision ID: ff23c634d4d7
Revises: 557a8a09a750
Create Date: 2026-08-21 10:31:35.288221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff23c634d4d7'
down_revision = '557a8a09a750'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ballot_pen_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ballot_pen_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('active_session_token', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('candidate_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('elector_submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('elector_id', sa.Integer(), nullable=False),
    sa.Column('elector_code', sa.String(length=120), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=True),
    sa.Column('surname', sa.String(length=120), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('district_name', sa.String(length=120), nullable=True),
    sa.Column('subdistrict_id', sa.Integer(), nullable=True),
    sa.Column('subdistrict_name', sa.String(length=120), nullable=True),
    sa.Column('municipality', sa.String(length=120), nullable=True),
    sa.Column('ballot_pen_id', sa.Integer(), nullable=True),
    sa.Column('ballot_number', sa.Integer(), nullable=True),
    sa.Column('polling_center_name', sa.String(length=150), nullable=True),
    sa.Column('room_name', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('political_allegiance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('elector_id', sa.Integer(), nullable=True),
    sa.Column('ballot_pen_id', sa.Integer(), nullable=True),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('subdistrict_id', sa.Integer(), nullable=True),
    sa.Column('sect_id', sa.Integer(), nullable=True),
    sa.Column('list_id', sa.Integer(), nullable=True),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_list_id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('subdistrict_id', sa.Integer(), nullable=True),
    sa.Column('sect_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('political_allegiance_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_list_id'], ['candidate_list.id'], ),
    sa.ForeignKeyConstraint(['political_allegiance_id'], ['political_allegiance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('district_account')
    op.drop_table('ballot_pen')
    op.drop_table('user')
    op.drop_table('subdistrict')
    op.drop_table('subdistrict_sect_seat')
    op.drop_table('party')
    op.drop_table('ballot_pen_sect')
    op.drop_table('sect')
    op.drop_table('district')
    with op.batch_alter_table('elector', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_elector_elector_id'))

    op.drop_table('elector')
    op.drop_table('polling_centers')
    op.drop_table('tenant_district')
    op.drop_table('tenant')
    op.drop_table('rooms')
    op.drop_table('user_ballot_pen')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_ballot_pen',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('ballot_pen_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['ballot_pen_id'], ['ballot_pen.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'ballot_pen_id')
    )
    op.create_table('rooms',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('polling_center_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['polling_center_id'], ['polling_centers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenant',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), nullable=False),
    sa.Column('db_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('party_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['party_id'], ['party.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('tenant_district',
    sa.Column('tenant_id', sa.INTEGER(), nullable=False),
    sa.Column('district_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['district.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('tenant_id', 'district_id')
    )
    op.create_table('polling_centers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('code', sa.VARCHAR(length=50), nullable=True),
    sa.Column('district_id', sa.INTEGER(), nullable=False),
    sa.Column('subdistrict_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['district.id'], ),
    sa.ForeignKeyConstraint(['subdistrict_id'], ['subdistrict.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('elector',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('elector_id', sa.VARCHAR(length=120), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=120), nullable=True),
    sa.Column('surname', sa.VARCHAR(length=120), nullable=True),
    sa.Column('family_name', sa.VARCHAR(length=120), nullable=True),
    sa.Column('father_name', sa.VARCHAR(length=120), nullable=True),
    sa.Column('mother_name', sa.VARCHAR(length=120), nullable=True),
    sa.Column('gender', sa.VARCHAR(length=10), nullable=True),
    sa.Column('dob', sa.DATE(), nullable=True),
    sa.Column('district_id', sa.INTEGER(), nullable=False),
    sa.Column('subdistrict_id', sa.INTEGER(), nullable=False),
    sa.Column('register', sa.VARCHAR(length=120), nullable=True),
    sa.Column('register_number', sa.INTEGER(), nullable=True),
    sa.Column('municipality', sa.VARCHAR(length=120), nullable=True),
    sa.Column('address', sa.VARCHAR(length=255), nullable=True),
    sa.Column('is_dead', sa.BOOLEAN(), nullable=True),
    sa.Column('registered', sa.BOOLEAN(), nullable=True),
    sa.Column('uploaded_at', sa.DATETIME(), nullable=True),
    sa.Column('birth_sect_id', sa.INTEGER(), nullable=True),
    sa.Column('current_sect_id', sa.INTEGER(), nullable=True),
    sa.Column('ballot_pen_id', sa.INTEGER(), nullable=True),
    sa.Column('ballot_number', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['ballot_pen_id'], ['ballot_pen.id'], name=op.f('fk_elector_ballot_pen')),
    sa.ForeignKeyConstraint(['birth_sect_id'], ['sect.id'], name=op.f('fk_birth_sect')),
    sa.ForeignKeyConstraint(['current_sect_id'], ['sect.id'], name=op.f('fk_current_sect')),
    sa.ForeignKeyConstraint(['district_id'], ['district.id'], name=op.f('fk_district')),
    sa.ForeignKeyConstraint(['subdistrict_id'], ['subdistrict.id'], name=op.f('fk_subdistrict')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('elector', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_elector_elector_id'), ['elector_id'], unique=False)

    op.create_table('district',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('code', sa.VARCHAR(length=10), nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('sect',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), nullable=False),
    sa.Column('religion', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ballot_pen_sect',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ballot_pen_id', sa.INTEGER(), nullable=False),
    sa.Column('sect_id', sa.INTEGER(), nullable=False),
    sa.Column('register_from', sa.INTEGER(), nullable=True),
    sa.Column('register_to', sa.INTEGER(), nullable=True),
    sa.Column('register_count', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['ballot_pen_id'], ['ballot_pen.id'], ),
    sa.ForeignKeyConstraint(['sect_id'], ['sect.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('party',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('subdistrict_sect_seat',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('subdistrict_id', sa.INTEGER(), nullable=False),
    sa.Column('sect_id', sa.INTEGER(), nullable=False),
    sa.Column('seats', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['sect_id'], ['sect.id'], ),
    sa.ForeignKeyConstraint(['subdistrict_id'], ['subdistrict.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subdistrict_id', 'sect_id', name=op.f('uq_subdistrict_sect'))
    )
    op.create_table('subdistrict',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('district_id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=120), nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['district.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), nullable=True),
    sa.Column('district_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['district.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('ballot_pen',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('polling_center_id', sa.INTEGER(), nullable=False),
    sa.Column('room_id', sa.INTEGER(), nullable=True),
    sa.Column('gender_type', sa.VARCHAR(length=20), nullable=True),
    sa.Column('voters_count', sa.INTEGER(), nullable=True),
    sa.Column('notes', sa.VARCHAR(length=255), nullable=True),
    sa.Column('serial_number', sa.VARCHAR(length=120), nullable=False),
    sa.Column('district_id', sa.INTEGER(), nullable=False),
    sa.Column('subdistrict_id', sa.INTEGER(), nullable=False),
    sa.Column('village', sa.VARCHAR(length=150), nullable=True),
    sa.Column('code', sa.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['district.id'], ),
    sa.ForeignKeyConstraint(['polling_center_id'], ['polling_centers.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['subdistrict_id'], ['subdistrict.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('district_account',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), nullable=True),
    sa.Column('district_id', sa.INTEGER(), nullable=True),
    sa.Column('username', sa.VARCHAR(length=100), nullable=True),
    sa.Column('password', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['district.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.drop_table('candidate')
    op.drop_table('vote')
    op.drop_table('political_allegiance')
    op.drop_table('elector_submission')
    op.drop_table('candidate_list')
    op.drop_table('ballot_pen_account')
    # ### end Alembic commands ###
